name: Update Release Description

on:
  release:
    types:
      - created

jobs:
  update_release_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        run: gh release create ${{ github.event.release.tag_name }} --title ${{ github.event.release.tag_name }} --notes ""

      - name: Update Release Description
        run: |
          echo "bla bla" | gh release edit ${{ github.event.release.tag_name }} --notes -
