name: Update Release Description

on:
  release:
    types:
      - created

jobs:
  update_release_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Release Description
        run: |
          # Get the tag name of the newly created release
          tag_name=$(git describe --tags --abbrev=0 ${{ github.event.release.commit_id }})
          
          # Add your custom text to the existing release description
          new_description="${{ github.event.release.body }}"$'\n'"bla bla"
          
          # Update the release using the updated description
          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"body": "'"$new_description"'"}' "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}"
