name: Update Release Description

on:
  release:
    types:
      - created

jobs:
  update_release_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Release Description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the last release's tag name using gh CLI
          last_tag=$(gh release list --limit 1 | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')

          # Check if the current release is the last one
          if [ "${{ github.event.release.tag_name }}" = "$last_tag" ]; then
            # Append "bla bla" to the release description using gh CLI
            gh release edit "${{ github.event.release.tag_name }}" --notes="${{ github.event.release.body }}"$'\n'"bla bla"
          else
            echo "This is not the last release. Skipping update."
          fi
