name: Update Release Notes

on:
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        run: npx semantic-release

      - name: Update Release Description
        run: |
          # Get the latest release ID
          release_id=$(curl -s -X GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq '.id')

          # Get the generated release notes from semantic-release
          release_notes=$(curl -s -X GET "https://api.github.com/repos/${{ github.repository }}/releases/${release_id}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq '.body')

          # Update the release description with the release notes
          curl -s -X PATCH "https://api.github.com/repos/${{ github.repository }}/releases/${release_id}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d "{\"body\": $release_notes}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
